name: Vuln Check
on: [push]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: govulncheck
        uses: golang/govulncheck-action@357ea4a5418cb457db33ccd168e28f68e075eba0
        with:
          go-version-input: 1.25.5
          go-package: ./...
